accounts:
  - name: bob
    coins: ["20000token", "200000000stake"]
  - name: relayer
    address: "cosmos1lahx0cvyyfldcd2yf29rk2tadlepjn58elfk54"
    coins: ["20000token", "200000000stake"]
validator:
  name: bob
  staked: "100000000stake"

init:
  home: "~/.chat-2"

genesis:
  chain_id: "chat-2"

host:
  rpc: ":36657"
  p2p: ":36658"
  prof: ":7060"
  grpc: ":10991"
  grpc-web: ":10093"
  api: ":2337"
