accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
  - name: relayer
    address: "cosmos1lahx0cvyyfldcd2yf29rk2tadlepjn58elfk54"
    coins: ["20000token", "200000000stake"]
validator:
  name: alice
  staked: "100000000stake"

init:
  home: "~/.chat-1"

genesis:
  chain_id: "chat-1"

host:
  rpc: ":26657"
  p2p: ":26658"
  prof: ":6060"
  grpc: ":9091"
  grpc-web: ":9093"
  api: ":1337"
